"""Hand-authored UI copy for the site_text tab. Not derived from the handbook --
edit this (or the Sheet, once published) to change any string the site shows."""

SITE_TEXT = [
    {"key": "site.title", "text": "Digital Ceasefire Platform", "notes": "Browser tab title / header"},
    {"key": "nav.home", "text": "Home", "notes": ""},
    {"key": "nav.handbook", "text": "Handbook", "notes": ""},
    {"key": "nav.builder", "text": "Build an Agreement", "notes": ""},
    {"key": "nav.updates", "text": "Updates", "notes": ""},

    {"key": "home.hero_title", "text": "Digital Ceasefire & Deescalation Handbook", "notes": ""},
    {"key": "home.hero_subtitle",
     "text": "A working framework mediators, negotiators, and conflict parties can use to negotiate and draft the Digital components of ceasefire and deescalation agreements.",
     "notes": ""},
    {"key": "home.cta_read", "text": "Read the Handbook", "notes": "Button to /handbook"},
    {"key": "home.cta_build", "text": "Build an Agreement", "notes": "Button to /builder"},
    {"key": "home.cta_review", "text": "Become a Reviewer", "notes": "Button to registration form"},
    {"key": "home.category_internet_interference", "text": "Internet Interference",
     "notes": "One of the three prohibited-operations categories, shown on Home"},
    {"key": "home.category_internet_interference.desc",
     "text": "Shutdowns, attacks on infrastructure, and jamming that cut people off from the internet.", "notes": ""},
    {"key": "home.category_information_threats", "text": "Information Threats", "notes": ""},
    {"key": "home.category_information_threats.desc",
     "text": "Disinformation, hate speech, incitement, doxxing, and manipulated media used to escalate conflict.", "notes": ""},
    {"key": "home.category_cyber_attacks", "text": "Cyber Attacks", "notes": ""},
    {"key": "home.category_cyber_attacks.desc",
     "text": "Hacking, malware, DDoS, phishing, and surveillance directed at people and infrastructure.", "notes": ""},

    {"key": "roles", "text": "NGO / civil society|Lawyer / legal scholar|Technical expert|Mediator / negotiator|Government|International organization|Academic|Other",
     "notes": "Fixed reviewer role list, pipe-separated, used by the registration form and role badges"},

    {"key": "context.armed_conflict.example", "text": "e.g. an international or non-international Armed Conflict under International Humanitarian Law.", "notes": "One-line example shown under the Armed Conflict option in Builder step 1"},
    {"key": "context.grey_zone.example", "text": "e.g. coercive or destabilizing activity below the threshold of Armed Conflict.", "notes": "Builder step 1"},
    {"key": "context.internal_disturbance.example", "text": "e.g. serious internal disorder, such as riots, that does not amount to Armed Conflict.", "notes": "Builder step 1"},

    {"key": "builder.step1_title", "text": "What kind of situation is this agreement for?", "notes": ""},
    {"key": "builder.step1_help", "text": "This sets which provisions are suggested first. You can change it later in Settings.", "notes": ""},
    {"key": "builder.start_empty", "text": "Start empty instead", "notes": ""},
    {"key": "builder.continue", "text": "Continue", "notes": ""},
    {"key": "builder.library_title", "text": "Provision library", "notes": ""},
    {"key": "builder.library_search_placeholder", "text": "Search provisions...", "notes": ""},
    {"key": "builder.agreement_title", "text": "Your agreement", "notes": ""},
    {"key": "builder.add_button", "text": "Add to my agreement", "notes": "Button in the handbook reader and the library"},
    {"key": "builder.added_badge", "text": "Added", "notes": ""},
    {"key": "builder.suggested_badge", "text": "Suggested for this context", "notes": ""},
    {"key": "builder.edited_badge", "text": "Edited", "notes": ""},
    {"key": "builder.restore_original", "text": "Restore original text", "notes": ""},
    {"key": "builder.remove", "text": "Remove", "notes": ""},
    {"key": "builder.add_custom_provision", "text": "Add a custom provision", "notes": ""},
    {"key": "builder.add_custom_definition", "text": "Add a custom definition", "notes": ""},
    {"key": "builder.pin", "text": "Pin", "notes": "Keep an auto-attached definition/law clause even if unused"},
    {"key": "builder.unpin", "text": "Unpin", "notes": ""},
    {"key": "builder.settings", "text": "Settings", "notes": ""},
    {"key": "builder.parties_label", "text": "Parties", "notes": "Settings panel: list of party names filling [Party A] etc."},
    {"key": "builder.entry_into_force_label", "text": "Entry into force", "notes": ""},
    {"key": "builder.saved_indicator", "text": "Saved", "notes": ""},
    {"key": "builder.new_draft", "text": "New draft", "notes": ""},
    {"key": "builder.export_docx", "text": "Export as Word (.docx)", "notes": ""},
    {"key": "builder.export_markdown", "text": "Export as Markdown", "notes": ""},
    {"key": "builder.export_print", "text": "Print / Save as PDF", "notes": ""},
    {"key": "builder.include_footnotes", "text": "Include footnotes", "notes": "Export toggle"},
    {"key": "builder.export_signature_block", "text": "Signatures", "notes": "Export section heading"},
    {"key": "builder.export_definitions_heading", "text": "Definitions", "notes": ""},
    {"key": "builder.export_annex_heading", "text": "Annex on Commitment to International Law", "notes": ""},
    {"key": "builder.undefined_terms_warning",
     "text": "These capitalized terms are used in your agreement but have no definition:",
     "notes": ""},
    {"key": "builder.context_change_confirm_title", "text": "Change context?", "notes": ""},
    {"key": "builder.context_change_confirm_body",
     "text": "Add this context's suggested provisions and remove unedited suggestions from the old one? Anything you edited, pinned, or added by hand stays.",
     "notes": ""},

    {"key": "review.comment_button", "text": "Comment", "notes": ""},
    {"key": "review.reply_button", "text": "Reply", "notes": ""},
    {"key": "review.reviewing_as", "text": "Reviewing as", "notes": "e.g. \"Reviewing as Lawyer / legal scholar\""},
    {"key": "review.sign_out", "text": "Sign out", "notes": ""},
    {"key": "review.comment_removed", "text": "Comment removed", "notes": "Shown in place of a hidden parent comment"},
    {"key": "review.comment_on_earlier_version",
     "text": "This comment was left on an earlier version of this text.", "notes": ""},
    {"key": "review.filter_open_only", "text": "Open threads only", "notes": ""},
    {"key": "review.register_title", "text": "Become a reviewer", "notes": ""},
    {"key": "review.register_pending",
     "text": "Thanks -- we'll email you once your reviewer access is approved.", "notes": ""},

    {"key": "error.rate_limited", "text": "You're commenting faster than we can keep up. Try again in a minute.", "notes": "Maps to Apps Script code rate_limited"},
    {"key": "error.invalid_token", "text": "Your reviewer link has expired or been revoked. Ask an admin to resend it.", "notes": "Maps to code invalid_token"},
    {"key": "error.body_too_long", "text": "That comment is too long (4,000 characters max).", "notes": "Maps to code body_too_long"},
    {"key": "error.selection_too_long", "text": "Please select a shorter passage to comment on.", "notes": "Maps to code selection_too_long"},
    {"key": "error.network", "text": "Couldn't reach the server. Your comment hasn't been posted -- try again.", "notes": ""},

    {"key": "footer.data_source", "text": "Content is maintained by the Digital Ceasefire Initiative and updates automatically.", "notes": ""},
    {"key": "footer.disclaimer", "text": "This tool assembles model language for discussion. It is not legal advice.", "notes": ""},
]
